export const tracks = {
  SEARCHING: "SEARCHING",
  SEARCHED_TERM: "SEARCHED_TERM",
  TOP_CHARTS: "TOP_CHARTS",
  SEARCH_PARAMETER: "SEARCH_PARAMETER",
  GETTNG_ARTIST_DETAILS: "GETTNG_ARTIST_DETAILS",
  ARTIST_DETAILS: "ARTIST_DETAILS",
  GETTING_ARTIST_TOP_TRACKS: "GETTING_ARTIST_TOP_TRACKS",
  ARTIST_TOP_TRACKS: "ARTIST_TOP_TRACKS",
};
